"""added patient_id to appointments

Revision ID: 04456817c353
Revises: d78d2fc91dec
Create Date: 2023-07-18 12:05:28.170821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04456817c353'
down_revision = 'd78d2fc91dec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_patient_id_patients'), 'patients', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_patient_id_patients'), type_='foreignkey')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
